project:
  type: website

website:
  title: "385website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: ae03-gerrymander.qmd
sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Assignments"
        contents:
        - href: ae03-gerrymander.qmd

format:
  html:
    theme:
      light: minty
      dark: cosmo
    css: styles.css
    toc: true



